#Varibale : Who Stores Data...
#Data Type : A Container who Stores Multiple Variables With Same Data type... 

#Varibales In Python...


#Rules To Define varibales In Python...

# [1] Name are Case sensitive...(var/VAR)
# [2] Varibale Always Starts With any Letter or '_' (underscore)...
# [3] Varibale Contains Letters, Digits and Underscore...
# [4] Don't Define Varible with Python Keywords...
# [5] Varibale Name Should be Meaningful...

#varible Defining With Different Data Types...

# [1] Basic Data Types...
var1 = 10 #int
var2 = 20.5 #float
var3 = "Hello" #string
var4 = True #bool --> True '1' or False '0'





